name: Deploy cloud functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up google cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy function 'tado-window-close'
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          name: tado-window-close
          runtime: go113
          entry_point: CloseWindow
          region: ${{ secrets.GCP_REGION }}
          env_vars: GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
